[package]
name = "skybound"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false, features = [
    "dynamic_linking", # Don't enable when building for release
    "wayland",

    "std",
    "async_executor",
    "bevy_core_pipeline",
    "bevy_anti_aliasing",
    "bevy_gizmos",
    "bevy_log",
    "bevy_pbr",
    "bevy_ui_render",
    "bevy_window",
    "default_font",
    "hdr",
    "multi_threaded",
    "tonemapping_luts",
    "zstd_rust",

    "debug",
] }
rand = "0.9.2"
bytemuck = "1.23.2"
image = "0.25.6"
rayon = "1.10.0"
bincode = { version = "2.0.1", features = ["serde"] }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

must_use_candidate = "allow"
type_complexity = "allow"
suboptimal_flops = "allow"
needless_pass_by_value = "allow"
similar_names = "allow"
cast_precision_loss = "allow"
cast_sign_loss = "allow"
cast_possible_truncation = "allow"
many_single_char_names = "allow"
inline_always = "allow"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
