[package]
name = "skybound"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false, features = [
    "dynamic_linking", # Don't enable when building for release
    "wayland",

    "std",
    "async_executor",
    "bevy_core_pipeline",
    "bevy_anti_aliasing",
    "bevy_log",
    "bevy_pbr",
    "bevy_ui_render",
    "bevy_window",
    "default_font",
    "hdr",
    "multi_threaded",
    "tonemapping_luts",
    "zstd_rust",
] }
noiz = "0.2.0"
rand = "0.9.1"
bytemuck = "1.23.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
