[package]
name = "skybound"
version = "0.1.0"
edition = "2024"

[dependencies]
skybound_gpu = { path = "../skybound_gpu" }
bevy = { git = "https://github.com/bevyengine/bevy", rev = "74884ffda7831d2b4576ade270199d671bb2e8f9", default-features = false, features = [
    "wayland",
    "std",
    "async_executor",
    "bevy_asset",
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_log",
    "bevy_post_process",
    "bevy_window",
    "bevy_render",
    "shader_format_spirv",
    "bevy_ui",
    "bevy_ui_render",
    "default_font",
    "hdr",
    "multi_threaded",
    "tonemapping_luts",
    "zstd_rust",
] }
bytemuck.workspace = true
image = { version = "0.25.10", default-features = false, features = ["png"] }
rand = "0.10.3"
rayon = "1.12.0"
clap = { version = "4.6.7", features = ["derive"] }

[build-dependencies]
spirv-builder.workspace = true

[lints]
workspace = true
